// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpwwbjmmtphcssuhxskb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwd3diam1tdHBoY3NzdWh4c2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDA4MjUsImV4cCI6MjA3MDQxNjgyNX0.m_anNYZBjdmriTUW9rmdTAgPrJXYzV1PeGl82E0COfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});